// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.LotteryNumberGenerator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("game")]
        public string Game { get; set; }

        [JsonProperty("game_type")]
        public string GameType { get; set; }

        [JsonProperty("config")]
        public Config Config { get; set; }

        [JsonProperty("tickets_generated")]
        public long? TicketsGenerated { get; set; }

        [JsonProperty("tickets")]
        public Ticket[] Tickets { get; set; }
    }

    public partial class Config
    {
        [JsonProperty("main_numbers_count")]
        public long? MainNumbersCount { get; set; }

        [JsonProperty("main_numbers_range")]
        public string MainNumbersRange { get; set; }

        [JsonProperty("bonus_numbers_count")]
        public long? BonusNumbersCount { get; set; }

        [JsonProperty("bonus_numbers_range")]
        public string BonusNumbersRange { get; set; }
    }

    public partial class Ticket
    {
        [JsonProperty("ticket_number")]
        public long? TicketNumber { get; set; }

        [JsonProperty("main_numbers")]
        public long?[] MainNumbers { get; set; }

        [JsonProperty("bonus_numbers")]
        public long?[] BonusNumbers { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
